theme: jekyll-theme-cayman
defaults:
  - scope:
      path: "assets/img"
    values:
      image: true

collections:
  events:
    output: true
    permalink: /:collection/:name
  usergroups:
    output: true
    permalink: /:collection/:name
  speakers:
    output: true
    permalink: /:collection/:name