theme: jekyll-theme-cayman
defaults:
  - scope:
      path: "assets/img"
    values:
      image: true
  - scope:
      path: ""
      type: events
    values:
      layout: default
  - scope:
      path: ""
      type: usergroups
    values:
      layout: default
  - scope:
      path: ""
      type: speakers
    values:
      layout: default

collections:
  events:
    output: true
    permalink: /events/:name
  usergroups:
    output: true
    permalink: /usergroups/:name
  speakers:
    output: true
    permalink: /speakers/:name